version: 2
jobs:
  test-parallel:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
         name: Intalando dependencia
         command: npm install
      - run:
         name: Pruebas
         command: npm run karma